-- -----------------------------------------------------
-- Schema HELP_DESK
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `systmlab_HELP_DESK` ;

-- -----------------------------------------------------
-- Schema HELP_DESK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systmlab_HELP_DESK` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `systmlab_HELP_DESK` ;

-- -----------------------------------------------------
-- Table `systmlab_HELP_DESK`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systmlab_HELP_DESK`.`USER` ;

CREATE TABLE IF NOT EXISTS `systmlab_HELP_DESK`.`USER` (
  `ID_USER` INT NOT NULL AUTO_INCREMENT,
  `ACCOUNT` VARCHAR(30) NOT NULL,
  `PASSWORD` VARCHAR(30) NOT NULL,
  `PATERNAL_NAME` VARCHAR(100) NOT NULL,
  `MATERNAL_NAME` VARCHAR(100) NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `DOCUMENT_TYPE` CHAR(1) NOT NULL COMMENT '1:DNI  2:INMIGRATION  CARD',
  `DOCUMENT_NUMBER` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `ROLE` CHAR(1) NOT NULL COMMENT '0:ADMIN 1:CLAIMANT 2:SERVIDESK OPERATOR 3:MICROTEC OPERATOR 4:SERVIDESK ADMIN 5:MICROTEC ADMIN',
  `STATE` CHAR(1) NOT NULL COMMENT '0:DISABLED  1:ENABLED',
  `ACTIVE` CHAR(1) NOT NULL COMMENT '0:INACTIVE  1:ACTIVE',
  `REGISTER_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `USER_ROLE_ID` INT NOT NULL,
PRIMARY KEY (`ID_USER`));

-- -----------------------------------------------------
-- Table `systmlab_HELP_DESK`.`LOCATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systmlab_HELP_DESK`.`LOCATION` ;

CREATE TABLE IF NOT EXISTS `systmlab_HELP_DESK`.`LOCATION` (
  `ID_LOCATION` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `ACTIVE` CHAR(1) NOT NULL COMMENT '0:INACTIVE  1:ACTIVE',
  `REGISTER_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `USER_ROLE_ID` INT NOT NULL,
PRIMARY KEY (`ID_LOCATION`));

-- -----------------------------------------------------
-- Table `systmlab_HELP_DESK`.`HALL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systmlab_HELP_DESK`.`HALL` ;

CREATE TABLE IF NOT EXISTS `systmlab_HELP_DESK`.`HALL` (
  `ID_HALL` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `PROVIDER` CHAR(1) NOT NULL COMMENT '1:SERVIDESCK  1:MICROTEC',
  `LOCATION_ID` INT NOT NULL,
  `ACTIVE` CHAR(1) NOT NULL COMMENT '0:INACTIVE  1:ACTIVE',
  `REGISTER_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `USER_ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID_HALL`),
  INDEX `LOCATION&HALL_IDX` (`LOCATION_ID` ASC),
  CONSTRAINT `LOCATION&HALL_C`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `systmlab_HELP_DESK`.`LOCATION` (`ID_LOCATION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `systmlab_HELP_DESK`.`DEVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systmlab_HELP_DESK`.`DEVICE` ;

CREATE TABLE IF NOT EXISTS `systmlab_HELP_DESK`.`DEVICE` (
  `ID_DEVICE` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(10) NOT NULL,
  `NAME` VARCHAR(30) NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `HALL_ID` INT NOT NULL,
  `ACTIVE` CHAR(1) NOT NULL COMMENT '0:INACTIVE  1:ACTIVE',
  `REGISTER_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `USER_ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID_DEVICE`),
  INDEX `HALL&DEVICE_IDX` (`HALL_ID` ASC),
  CONSTRAINT `HALL&DEVICE_C`
    FOREIGN KEY (`HALL_ID`)
    REFERENCES `systmlab_HELP_DESK`.`HALL` (`ID_HALL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- Table `systmlab_HELP_DESK`.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systmlab_HELP_DESK`.`CATEGORY` ;

CREATE TABLE IF NOT EXISTS `systmlab_HELP_DESK`.`CATEGORY` (
  `ID_CATEGORY` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `TYPE` CHAR(1) NOT NULL COMMENT '1:REQUIREMENT  2:INCIDENT',
  `DESCRIPTION` TEXT NULL,
  `DEVICE_REQUIRED` CHAR(1) NOT NULL COMMENT '0:NOT REQUIRED 1:REQUIRED',
  `ACTIVE` CHAR(1) NOT NULL COMMENT '0:INACTIVE  1:ACTIVE',
  `REGISTER_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `USER_ROLE_ID` INT NOT NULL,
PRIMARY KEY (`ID_CATEGORY`));

-- -----------------------------------------------------
-- Table `systmlab_HELP_DESK`.`REQUEST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `systmlab_HELP_DESK`.`REQUEST` ;

CREATE TABLE IF NOT EXISTS `systmlab_HELP_DESK`.`REQUEST` (
  `ID_REQUEST` INT NOT NULL AUTO_INCREMENT,
  `CODE` VARCHAR(10) NOT NULL,
  `DESCRIPTION` TEXT NOT NULL,
  `OBSERVATION` TEXT NULL,
  `FILE` VARCHAR(500) NULL,
  `START_DATE` DATETIME NOT NULL,
  `END_DATE` DATETIME NULL,
  `STATE` CHAR(1) NOT NULL COMMENT '1:ASGINADO  2:EN PROCESO 3:EN ESPERA 4:RESUELTO 5:NO RESUELTO',
  `EXPIRED` CHAR(1) NOT NULL COMMENT '0:NO EXPIRADO  1:EXPIRADO',
  `USER_REQ_ID` INT NOT NULL,
  `USER_OPE_ID` INT NOT NULL,
  `CATEGORY_ID` INT NOT NULL,
  `DEVICE_ID` INT NULL,
  `ACTIVE` CHAR(1) NOT NULL COMMENT '0:INACTIVE  1:ACTIVE',
  `REGISTER_DATE` DATETIME NOT NULL,
  `UPDATE_DATE` DATETIME NOT NULL,
  `USER_ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID_REQUEST`),
  INDEX `USER_REQ&REQUEST_IDX` (`USER_REQ_ID` ASC),
  INDEX `USER_OP&REQUEST_IDX` (`USER_OPE_ID` ASC),
  INDEX `DEVICE&REQUEST_IDX` (`DEVICE_ID` ASC),
  INDEX `CATEGORY&REQUEST_IDX` (`CATEGORY_ID` ASC),
  CONSTRAINT `USER_REQ&REQUEST_C`
    FOREIGN KEY (`USER_REQ_ID`)
    REFERENCES `systmlab_HELP_DESK`.`USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USER_OP&REQUEST_C`
    FOREIGN KEY (`USER_OPE_ID`)
    REFERENCES `systmlab_HELP_DESK`.`USER` (`ID_USER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CATEGORY&REQUEST_C`
    FOREIGN KEY (`CATEGORY_ID`)
    REFERENCES `systmlab_HELP_DESK`.`CATEGORY` (`ID_CATEGORY`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DEVICE&REQUEST_C`
    FOREIGN KEY (`DEVICE_ID`)
    REFERENCES `systmlab_HELP_DESK`.`DEVICE` (`ID_DEVICE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

-- -----------------------------------------------------
-- commit
-- -----------------------------------------------------

COMMIT;